### ISSUE TITLE
Right axis labels start behind the axis

### ISSUE THREAD

**Issue by alxpl** [SciDAVis/scidavis#12]
Hello,

I needed to rework some of my plots for my thesis manuscript and I noticed that on all the plots with an axis on the right, the labels appear to be drawn partly below the axis, so instead of showing "0.2", I get just the "2" with the major tick right through the number.
I'm not sure when this appeared, I hadn't touched a file with plots containing a second axis since June and there were no problems then. Looking at the updates I've pushed to Fedora in between, there was a rebuild with the latest version of qwtplot3d-qt5 (the fork maintained by Miquel) in July and I wonder if that might be the cause, unless it's due to one of the runtime dependencies of SciDAVis.
Can anyone reproduce this? Any ideas?

![Screenshot from 2021-10-27 23-29-05](https://user-images.githubusercontent.com/9637949/139151711-3a7f74a6-7c44-42b1-99fa-44e1bbf2a996.png)

**Comment by gbm19** [comment]
Sorry for the delay. Just got aware of the issue. 

Attached patch solves the issues: 
    [SciDAVis gh#12](https://github.com/SciDAVis/scidavis/issues/12)
    [Bug sf#406](https://sourceforge.net/p/scidavis/scidavis-bugs/406/)
    [Bug sf#418](https://sourceforge.net/p/scidavis/scidavis-bugs/418/)


[fix-issue-gh12-right-axis-labels-behind-axis.patch.txt](https://github.com/SciDAVis/scidavis/files/7488030/fix-issue-gh12-right-axis-labels-behind-axis.patch.txt)

**Comment by alxpl** [comment]
Thank you so much, I'm going to push an update to every branch in Fedora soon.
Are you going to submit a PR (or just merge the code)?

**Comment by alxpl** [comment]
> Thank you so much, I'm going to push an update to every branch in Fedora soon.

Turns out there's a problem with sip (and PyQt5?) in F35 and F36, so only F34 is getting the update for now. I'm investigating the issue.

**Comment by alxpl** [comment]
> Turns out there's a problem with sip (and PyQt5?) in F35 and F36, so only F34 is getting the update for now. I'm investigating the issue.

Scott's [PR](https://github.com/SciDAVis/scidavis/pull/14) fixes the issues with sip6 and with that SciDAVis can be built again on all Fedora branches.
