### ISSUE TITLE
Unable to install SciDAVis on Ubuntu 21.04

### ISSUE THREAD

**Issue by serraedoardo** [SciDAVis/scidavis#16]
I'm new to Linux so forgive me if what I'm reporting has a simple solution.

When I upgraded my virtual machine from Ubuntu 20.04 to Ubuntu 21.04 it uninstalled SciDAVis, and since then I have been unable to install it again or to find a solution online.

When running `sudo apt-get install scidavis` it returns me the following:
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 scidavis : Depends: libgsl23 (>= 2.5) but it is not installable
            Depends: libpython3.8 (>= 3.8.2) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

Can it somehow be fixed? Thank you.

**Comment by highperformancecoder** [comment]
Did you follow the instructions for 21.04 at
https://software.opensuse.org//download.html?project=home%3Ahpcoder1&package=scidavis?

You will need to remove an re-add the correct distro repository for
hpcoder1, as you have changed the Ubuntu version. 20.04 packages will not
typically work in 21.04, for example. Hopefully, this works for you.

Note that currently the scidavis build on OBS is broken, but I see that scidavis
2.4.1 has been built for 21.04, but not for 21.10.

Unfortunately, I am again horrendously busy, and unlikely to have the
time to look into it until next February, probably.

Cheers

On Sat, Nov 20, 2021 at 02:37:39PM -0800, Italiandrache wrote:
> I'm new to Linux so forgive me if what I'm reporting has a simple solution.
> 
> When I upgraded my virtual machine from Ubuntu 20.04 to Ubuntu 21.04 it
> uninstalled SciDAVis, and since then I have been unable to install it again or
> to find a solution online.
> 
> When running sudo apt-get install scidavis it returns me the error:
> `Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
> scidavis : Depends: libgsl23 (>= 2.5) but it is not installable
> Depends: libpython3.8 (>= 3.8.2) but it is not installable
> E: Unable to correct problems, you have held broken packages.`
> 
> Can it somehow be fixed? Thank you.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. *
> 

-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders     ***@***.***
                      http://www.hpcoders.com.au
----------------------------------------------------------------------------

**Comment by serraedoardo** [comment]
Thank you, it worked. I'm closing the issue since it is resolved.
